# Generated by Django 4.2.10 on 2024-02-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0002_alter_brand_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="brand",
            old_name="slug",
            new_name="ref",
        ),
    ]
