# Generated by Django 4.2.10 on 2024-02-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0003_rename_slug_brand_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="Brands"),
        ),
    ]
