# Generated by Django 4.2.10 on 2024-03-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0004_alter_brand_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="Categories"),
                ),
                ("create_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ref",
                    models.SlugField(
                        allow_unicode=True, blank=True, max_length=120, unique=True
                    ),
                ),
            ],
        ),
    ]
