# Generated by Django 4.2.10 on 2024-03-06 18:04

import Product.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0007_alter_subcategory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price", models.PositiveIntegerField(default=0)),
                (
                    "imageCover",
                    models.ImageField(
                        upload_to=Product.models.Product.uploadProductCoverImagePath
                    ),
                ),
                ("ref", models.CharField(max_length=500)),
            ],
            options={
                "ordering": ["ref", "created_at", "updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="brand",
            options={"ordering": ["ref", "created_at", "updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["ref", "created_at", "updated_at"]},
        ),
        migrations.CreateModel(
            name="Productmages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=Product.models.Productmages.uploadToPath
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Product.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Product.brand",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Product.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Product.subcategory",
            ),
        ),
    ]
